version: "3"
services:

    # Backend API
    api:
      build: .
      ports: 
        - "3001:3001"
      command: npm start
      environment: 
        DB_URI: postgres://erik:password@database:5432/press_express

    # Postgres
    database:
      image: postgres:9
      ports: 
        - "5432:5432"
      environment: 
        POSTGRES_PASSWORD: password
      volumes: 
        - "$HOME/docker/volumes/postgres:/var/lib/postgresql/data"
            
